version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
  #     PORT: 3001

  frontend:
    build: ./frontendapp
    container_name: frontendapp
    restart: unless-stopped
    # depends_on:
    #   - backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: 3000
